version: '3'

services:

  frontend:
    image: ghcr.io/authenticationproject/frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - adminmicroservice
    networks:
      appnet:

  adminmicroservice:
    image: ghcr.io/authenticationproject/adminmicroservice:latest
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/AdminMicroservice
      SPRING_DATASOURCE_USERNAME: user_name
      SPRING_DATASOURCE_PASSWORD: root_password
    networks:
      appnet:

  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password -h 127.0.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: AdminMicroservice
      MYSQL_USER: user_name
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      appnet:
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      appnet:

  reverse-proxy:
    image: caddy:2
    container_name: caddy_proxy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      appnet:

volumes:
  dbdata:
  caddy_data:
  caddy_config:

networks:
  appnet:
    driver: bridge