spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: superdani.d@gmail.com
    password: hjmn vcpg phck lkcr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true